### ISSUE TITLE
[BUG] Calls and Video Calls do not appear in Firefox browser

### ISSUE THREAD

**Issue by DMJWorld** [morethanwords/tweb#106]
Calls and video calls do not appear in Firefox browser. no icon and no item in the 3-dot menu
It seems that the problem, after tests with other browser, is only in Firefox.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox 98.0.2]
 - Web K Version [1.4.0]

**Comment by matthiasaechtner** [comment]
I can already tell that WebRTC is used for voicecalls, and I suspect that the fact that it does not work on Firefox is related to 
[https://en.wikipedia.org/wiki/WebRTC#Concerns](https://en.wikipedia.org/wiki/WebRTC#Concerns)
"In January 2015, TorrentFreak reported a serious security flaw in browsers that support WebRTC, saying that it compromised the security of VPN tunnels by exposing the true IP address of a user. [...] the uBlock Origin add-on can fix this problem (as **some browsers now fix this problem by themselves,** from uBlock Origin v1.38 onwards this option has been disabled on these browsers). As of September 2019, this WebRTC flaw **still surfaces on Firefox** 69.x and still by default exposes the user's internal IP address to the web. [..]"

**Comment by morethanwords** [comment]
> I can already tell that WebRTC is used for voicecalls, and I suspect that the fact that it does not work on Firefox is related to https://en.wikipedia.org/wiki/WebRTC#Concerns "In January 2015, TorrentFreak reported a serious security flaw in browsers that support WebRTC, saying that it compromised the security of VPN tunnels by exposing the true IP address of a user. [...] the uBlock Origin add-on can fix this problem (as **some browsers now fix this problem by themselves,** from uBlock Origin v1.38 onwards this option has been disabled on these browsers). As of September 2019, this WebRTC flaw **still surfaces on Firefox** 69.x and still by default exposes the user's internal IP address to the web. [..]"

It is not connected to that. It doesn't work yet because of SDP issues.

**Comment by DMJWorld** [comment]
> > I can already tell that WebRTC is used for voicecalls, and I suspect that the fact that it does not work on Firefox is related to https://en.wikipedia.org/wiki/WebRTC#Concerns "In January 2015, TorrentFreak reported a serious security flaw in browsers that support WebRTC, saying that it compromised the security of VPN tunnels by exposing the true IP address of a user. [...] the uBlock Origin add-on can fix this problem (as **some browsers now fix this problem by themselves,** from uBlock Origin v1.38 onwards this option has been disabled on these browsers). As of September 2019, this WebRTC flaw **still surfaces on Firefox** 69.x and still by default exposes the user's internal IP address to the web. [..]"
> 
> It is not connected to that. It doesn't work yet because of SDP issues.

A temporary solution I found was to change user-agent via plug-ins

**Comment by jzhng** [comment]
> > 
> > It is not connected to that. It doesn't work yet because of SDP issues.
> 
> A temporary solution I found was to change user-agent via plug-ins

Could make it appear but call not actually work.

**Comment by lattice0** [comment]
please make calls available on firefox

**Comment by alfredonodo** [comment]
> > I can already tell that WebRTC is used for voicecalls, and I suspect that the fact that it does not work on Firefox is related to https://en.wikipedia.org/wiki/WebRTC#Concerns "In January 2015, TorrentFreak reported a serious security flaw in browsers that support WebRTC, saying that it compromised the security of VPN tunnels by exposing the true IP address of a user. [...] the uBlock Origin add-on can fix this problem (as **some browsers now fix this problem by themselves,** from uBlock Origin v1.38 onwards this option has been disabled on these browsers). As of September 2019, this WebRTC flaw **still surfaces on Firefox** 69.x and still by default exposes the user's internal IP address to the web. [..]"
> 
> It is not connected to that. It doesn't work yet because of SDP issues.

Chromium abandoned the proprietary SDP plan B in favor of the standardized SDP unified plan since [version 101](https://webrtc.org/getting-started/unified-plan-transition-guide), so it should work now (version 108, [microsoft teams](https://github.com/webcompat/web-bugs/issues/25070#issuecomment-1346973196) has a similar problem).

**Comment by gmankab** [comment]
also don't work in ungoogled chromium

work in brave

**Comment by wanw73318-droid** [comment]
> [!NOTE]
>

**Comment by abacabadabacaba** [comment]
We have reached the state where WhatsApp has more features than Telegram. Because now calls work in WhatsApp Web, even in Firefox. When will Telegram catch up?

**Comment by lattice0** [comment]
@abacabadabacaba indeed. Nowadays you have to pay for features that whatsapp have for free, and telegram is still not e2e encrypted by default. What a mess.
